-- MySQL Script generated by MySQL Workbench
-- Seg 07 Mai 2018 19:46:38 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cliente_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_cliente_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_veiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`veiculo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_veiculo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_veiculo_tipo_veiculo1_idx` (`tipo_veiculo_id` ASC),
  CONSTRAINT `fk_veiculo_tipo_veiculo1`
    FOREIGN KEY (`tipo_veiculo_id`)
    REFERENCES `mydb`.`tipo_veiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`oficina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`oficina` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente_veiculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente_veiculo` (
  `cliente_id` INT NOT NULL,
  `veiculo_id` INT NOT NULL,
  PRIMARY KEY (`cliente_id`, `veiculo_id`),
  INDEX `fk_cliente_has_veiculo_veiculo1_idx` (`veiculo_id` ASC),
  INDEX `fk_cliente_has_veiculo_cliente_idx` (`cliente_id` ASC),
  CONSTRAINT `fk_cliente_has_veiculo_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `mydb`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cliente_has_veiculo_veiculo1`
    FOREIGN KEY (`veiculo_id`)
    REFERENCES `mydb`.`veiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario_oficina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario_oficina` (
  `usuario_id` INT NOT NULL,
  `oficina_id` INT NOT NULL,
  PRIMARY KEY (`usuario_id`, `oficina_id`),
  INDEX `fk_usuario_has_oficina_oficina1_idx` (`oficina_id` ASC),
  INDEX `fk_usuario_has_oficina_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_usuario_has_oficina_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_oficina_oficina1`
    FOREIGN KEY (`oficina_id`)
    REFERENCES `mydb`.`oficina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ordem_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ordem_servico` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `veiculo_id` INT NOT NULL,
  `servico_id` INT NOT NULL,
  `oficina_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ordem_servico_veiculo1_idx` (`veiculo_id` ASC),
  INDEX `fk_ordem_servico_servico1_idx` (`servico_id` ASC),
  INDEX `fk_ordem_servico_oficina1_idx` (`oficina_id` ASC),
  INDEX `fk_ordem_servico_cliente1_idx` (`cliente_id` ASC),
  INDEX `fk_ordem_servico_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_ordem_servico_veiculo1`
    FOREIGN KEY (`veiculo_id`)
    REFERENCES `mydb`.`veiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem_servico_servico1`
    FOREIGN KEY (`servico_id`)
    REFERENCES `mydb`.`servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem_servico_oficina1`
    FOREIGN KEY (`oficina_id`)
    REFERENCES `mydb`.`oficina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem_servico_cliente1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `mydb`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem_servico_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item` (
  `ordem_servico_id` INT NOT NULL,
  `produto_id` INT NOT NULL,
  `quantidade` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`ordem_servico_id`, `produto_id`),
  INDEX `fk_ordem_servico_has_produto_produto1_idx` (`produto_id` ASC),
  INDEX `fk_ordem_servico_has_produto_ordem_servico1_idx` (`ordem_servico_id` ASC),
  CONSTRAINT `fk_ordem_servico_has_produto_ordem_servico1`
    FOREIGN KEY (`ordem_servico_id`)
    REFERENCES `mydb`.`ordem_servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ordem_servico_has_produto_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `mydb`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`secretario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`secretario` (
  `oficina_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`oficina_id`, `usuario_id`),
  INDEX `fk_oficina_has_usuario_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_oficina_has_usuario_oficina1_idx` (`oficina_id` ASC),
  CONSTRAINT `fk_oficina_has_usuario_oficina1`
    FOREIGN KEY (`oficina_id`)
    REFERENCES `mydb`.`oficina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_oficina_has_usuario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servico_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servico_cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`veiculo_servico_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`veiculo_servico_cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NULL,
  `descricao` TEXT NULL,
  `servico_cliente_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  `veiculo_id` INT NOT NULL,
  INDEX `fk_veiculo_servico_cliente_servico_cliente1_idx` (`servico_cliente_id` ASC),
  INDEX `fk_veiculo_servico_cliente_usuario1_idx` (`usuario_id` ASC),
  INDEX `fk_veiculo_servico_cliente_veiculo1_idx` (`veiculo_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_veiculo_servico_cliente_servico_cliente1`
    FOREIGN KEY (`servico_cliente_id`)
    REFERENCES `mydb`.`servico_cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veiculo_servico_cliente_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_veiculo_servico_cliente_veiculo1`
    FOREIGN KEY (`veiculo_id`)
    REFERENCES `mydb`.`veiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_veiculo_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_veiculo_produto` (
  `produto_id` INT NOT NULL,
  `tipo_veiculo_id` INT NOT NULL,
  PRIMARY KEY (`produto_id`, `tipo_veiculo_id`),
  INDEX `fk_produto_has_tipo_veiculo_tipo_veiculo1_idx` (`tipo_veiculo_id` ASC),
  INDEX `fk_produto_has_tipo_veiculo_produto1_idx` (`produto_id` ASC),
  CONSTRAINT `fk_produto_has_tipo_veiculo_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `mydb`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_has_tipo_veiculo_tipo_veiculo1`
    FOREIGN KEY (`tipo_veiculo_id`)
    REFERENCES `mydb`.`tipo_veiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_veiculo_servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_veiculo_servico` (
  `tipo_veiculo_id` INT NOT NULL,
  `servico_id` INT NOT NULL,
  PRIMARY KEY (`tipo_veiculo_id`, `servico_id`),
  INDEX `fk_tipo_veiculo_has_servico_servico1_idx` (`servico_id` ASC),
  INDEX `fk_tipo_veiculo_has_servico_tipo_veiculo1_idx` (`tipo_veiculo_id` ASC),
  CONSTRAINT `fk_tipo_veiculo_has_servico_tipo_veiculo1`
    FOREIGN KEY (`tipo_veiculo_id`)
    REFERENCES `mydb`.`tipo_veiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_veiculo_has_servico_servico1`
    FOREIGN KEY (`servico_id`)
    REFERENCES `mydb`.`servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `oficina_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_funcionario_oficina1_idx` (`oficina_id` ASC),
  INDEX `fk_funcionario_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_funcionario_oficina1`
    FOREIGN KEY (`oficina_id`)
    REFERENCES `mydb`.`oficina` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_funcionario_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`servicos_realizados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`servicos_realizados` (
  `servico_id` INT NOT NULL,
  `ordem_servico_id` INT NOT NULL,
  `funcionario_id` INT NULL,
  PRIMARY KEY (`servico_id`, `ordem_servico_id`),
  INDEX `fk_servico_has_ordem_servico_ordem_servico1_idx` (`ordem_servico_id` ASC),
  INDEX `fk_servico_has_ordem_servico_servico1_idx` (`servico_id` ASC),
  INDEX `fk_servicos_realizados_funcionario1_idx` (`funcionario_id` ASC),
  CONSTRAINT `fk_servico_has_ordem_servico_servico1`
    FOREIGN KEY (`servico_id`)
    REFERENCES `mydb`.`servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servico_has_ordem_servico_ordem_servico1`
    FOREIGN KEY (`ordem_servico_id`)
    REFERENCES `mydb`.`ordem_servico` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicos_realizados_funcionario1`
    FOREIGN KEY (`funcionario_id`)
    REFERENCES `mydb`.`funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_veiculo_id` INT NOT NULL,
  `codigo_fipe` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_marca_tipo_veiculo1_idx` (`tipo_veiculo_id` ASC),
  CONSTRAINT `fk_marca_tipo_veiculo1`
    FOREIGN KEY (`tipo_veiculo_id`)
    REFERENCES `mydb`.`tipo_veiculo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modelo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marca_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_modelo_marca1_idx` (`marca_id` ASC),
  CONSTRAINT `fk_modelo_marca1`
    FOREIGN KEY (`marca_id`)
    REFERENCES `mydb`.`marca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ano` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `modelo_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ano_modelo1_idx` (`modelo_id` ASC),
  CONSTRAINT `fk_ano_modelo1`
    FOREIGN KEY (`modelo_id`)
    REFERENCES `mydb`.`modelo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
